<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>MenaceSnipersPromise</AssemblyName>
    <Version>0.3.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <GameDir Condition="'$(GameDir)' == ''">D:\Steam\steamapps\common\Menace</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Unity.InputSystem.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\Il2CppAssemblies\Il2CppSirenix.Serialization.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\net6\MelonLoader.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\net6\0Harmony.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\net6\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="$(GameDir)\MelonLoader\net6\UnityEngine.Il2CppImageConversionManager.dll" Private="false" />
  </ItemGroup>
</Project>
